# Generated by Django 5.0 on 2023-12-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpamDetectorAPI', '0002_alter_user_options_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
