# Generated by Django 5.0 on 2023-12-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpamDetectorAPI', '0003_rename_contacts_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
